apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.repository }}:{{ .Values.app.tag }}"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: myapp-config
            - secretRef:
                name: myapp-secret
          readinessProbe:           # ✅ 수정된 들여쓰기
            httpGet:
              path: /healthz
              port: 5000
          resources:                # ✅ readinessProbe 외부로 이동
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
