db:
  repository: public.ecr.aws/g1o9h9r6/cms-lab2
  tag: db-v2
  replicas: 1

redis:
  repository: public.ecr.aws/g1o9h9r6/cms-lab2
  tag: redis-v1
  replicas: 1

app:
  repository: public.ecr.aws/g1o9h9r6/cms-lab2
  tag: app-v1
  replicas: 2

nginx:
  repository: public.ecr.aws/g1o9h9r6/cms-lab2
  tag: nginx-v1
  replicas: 1


ingress:
  healthCheckPath: /healthz
  host: app.choiminseon.com
  certificateArn: arn:aws:acm:ap-northeast-1:862016452072:certificate/8ae435cf-fb09-4af0-a819-1876b2e42e2a

  group:
    name: shared-alb
    order: "10"
